disabled_rules: # rule identifiers to exclude from running
  - todo
  - trailing_comma
  - trailing_whitespace
  - type_body_length
# These are paths to ignore during linting. Takes precedence over `included`.
excluded:
  - GuidomiaTests
  - GuidomiaUITests
  - Guidomia/Generated
  - Guidomia/PreviewContent
# These are paths to include during linting. `--path` is ignored if present.
included: 
  - Guidomia
  
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
identifier_name:
  excluded:
    - id
line_length:
  ignores_comments: true
  warning: 120
  error: 150 
vertical_whitespace:
  max_empty_lines: 2